# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pipx
      run: |
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath
    - name: Install poetry
      run: |
        pipx install poetry
    - name: Install dependencies
      run: poetry install
    - name: Run pytest
      run: poetry run pytest
    - name: Pre-commit autoupdate
      run: poetry pre-commit autoupdate

