# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        vresion: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.version}}
        cache: 'poetry'
    - name: Install poetry
      run: pipx install poetry
    - name: Install dependencies
      run: poetry install
    - name: run pytest
      run: poetry run pytest
